name: Siri Shortcut

on: repository_dispatch  

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/create-an-issue@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
