name: Siri Shortcut

on: repository_dispatch  

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install
        working-directory: ./.github/issues-autolabeler
      - name: label_issue
        uses: ./.github/issues-autolabeler
        with:
          issue: ${{github.event.client_payload.description}}
        env:
          LUIS_APP_ID: ${{ secrets.LUIS_APP_ID }}
          LUIS_APP_KEY: ${{ secrets.LUIS_APP_KEY }}
      - uses: JasonEtco/create-an-issue@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          labels: ${{ env.ISSUE_LABEL }}
